/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Alumno;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Empresa
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-18T17:33:28.589002300+01:00[Europe/Madrid]", comments = "Generator version: 7.11.0")
public class Empresa {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Long id;

  public static final String SERIALIZED_NAME_NOMBRE_EMPRESA = "nombreEmpresa";
  @SerializedName(SERIALIZED_NAME_NOMBRE_EMPRESA)
  @javax.annotation.Nullable
  private String nombreEmpresa;

  public static final String SERIALIZED_NAME_TUTOR_LABORAL = "tutorLaboral";
  @SerializedName(SERIALIZED_NAME_TUTOR_LABORAL)
  @javax.annotation.Nullable
  private String tutorLaboral;

  public static final String SERIALIZED_NAME_EMAIL_TUTOR_LABORAL = "emailTutorLaboral";
  @SerializedName(SERIALIZED_NAME_EMAIL_TUTOR_LABORAL)
  @javax.annotation.Nullable
  private String emailTutorLaboral;

  public static final String SERIALIZED_NAME_TELEFONO_TUTOR_LABORAL = "telefonoTutorLaboral";
  @SerializedName(SERIALIZED_NAME_TELEFONO_TUTOR_LABORAL)
  @javax.annotation.Nullable
  private String telefonoTutorLaboral;

  public static final String SERIALIZED_NAME_ACTIVO = "activo";
  @SerializedName(SERIALIZED_NAME_ACTIVO)
  @javax.annotation.Nullable
  private Boolean activo;

  public static final String SERIALIZED_NAME_ALUMNOS = "alumnos";
  @SerializedName(SERIALIZED_NAME_ALUMNOS)
  @javax.annotation.Nullable
  private List<Alumno> alumnos = new ArrayList<>();

  public Empresa() {
  }

  public Empresa id(@javax.annotation.Nullable Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Long getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }


  public Empresa nombreEmpresa(@javax.annotation.Nullable String nombreEmpresa) {
    this.nombreEmpresa = nombreEmpresa;
    return this;
  }

  /**
   * Get nombreEmpresa
   * @return nombreEmpresa
   */
  @javax.annotation.Nullable
  public String getNombreEmpresa() {
    return nombreEmpresa;
  }

  public void setNombreEmpresa(@javax.annotation.Nullable String nombreEmpresa) {
    this.nombreEmpresa = nombreEmpresa;
  }


  public Empresa tutorLaboral(@javax.annotation.Nullable String tutorLaboral) {
    this.tutorLaboral = tutorLaboral;
    return this;
  }

  /**
   * Get tutorLaboral
   * @return tutorLaboral
   */
  @javax.annotation.Nullable
  public String getTutorLaboral() {
    return tutorLaboral;
  }

  public void setTutorLaboral(@javax.annotation.Nullable String tutorLaboral) {
    this.tutorLaboral = tutorLaboral;
  }


  public Empresa emailTutorLaboral(@javax.annotation.Nullable String emailTutorLaboral) {
    this.emailTutorLaboral = emailTutorLaboral;
    return this;
  }

  /**
   * Get emailTutorLaboral
   * @return emailTutorLaboral
   */
  @javax.annotation.Nullable
  public String getEmailTutorLaboral() {
    return emailTutorLaboral;
  }

  public void setEmailTutorLaboral(@javax.annotation.Nullable String emailTutorLaboral) {
    this.emailTutorLaboral = emailTutorLaboral;
  }


  public Empresa telefonoTutorLaboral(@javax.annotation.Nullable String telefonoTutorLaboral) {
    this.telefonoTutorLaboral = telefonoTutorLaboral;
    return this;
  }

  /**
   * Get telefonoTutorLaboral
   * @return telefonoTutorLaboral
   */
  @javax.annotation.Nullable
  public String getTelefonoTutorLaboral() {
    return telefonoTutorLaboral;
  }

  public void setTelefonoTutorLaboral(@javax.annotation.Nullable String telefonoTutorLaboral) {
    this.telefonoTutorLaboral = telefonoTutorLaboral;
  }


  public Empresa activo(@javax.annotation.Nullable Boolean activo) {
    this.activo = activo;
    return this;
  }

  /**
   * Get activo
   * @return activo
   */
  @javax.annotation.Nullable
  public Boolean getActivo() {
    return activo;
  }

  public void setActivo(@javax.annotation.Nullable Boolean activo) {
    this.activo = activo;
  }


  public Empresa alumnos(@javax.annotation.Nullable List<Alumno> alumnos) {
    this.alumnos = alumnos;
    return this;
  }

  public Empresa addAlumnosItem(Alumno alumnosItem) {
    if (this.alumnos == null) {
      this.alumnos = new ArrayList<>();
    }
    this.alumnos.add(alumnosItem);
    return this;
  }

  /**
   * Get alumnos
   * @return alumnos
   */
  @javax.annotation.Nullable
  public List<Alumno> getAlumnos() {
    return alumnos;
  }

  public void setAlumnos(@javax.annotation.Nullable List<Alumno> alumnos) {
    this.alumnos = alumnos;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Empresa empresa = (Empresa) o;
    return Objects.equals(this.id, empresa.id) &&
        Objects.equals(this.nombreEmpresa, empresa.nombreEmpresa) &&
        Objects.equals(this.tutorLaboral, empresa.tutorLaboral) &&
        Objects.equals(this.emailTutorLaboral, empresa.emailTutorLaboral) &&
        Objects.equals(this.telefonoTutorLaboral, empresa.telefonoTutorLaboral) &&
        Objects.equals(this.activo, empresa.activo) &&
        Objects.equals(this.alumnos, empresa.alumnos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nombreEmpresa, tutorLaboral, emailTutorLaboral, telefonoTutorLaboral, activo, alumnos);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Empresa {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nombreEmpresa: ").append(toIndentedString(nombreEmpresa)).append("\n");
    sb.append("    tutorLaboral: ").append(toIndentedString(tutorLaboral)).append("\n");
    sb.append("    emailTutorLaboral: ").append(toIndentedString(emailTutorLaboral)).append("\n");
    sb.append("    telefonoTutorLaboral: ").append(toIndentedString(telefonoTutorLaboral)).append("\n");
    sb.append("    activo: ").append(toIndentedString(activo)).append("\n");
    sb.append("    alumnos: ").append(toIndentedString(alumnos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("nombreEmpresa");
    openapiFields.add("tutorLaboral");
    openapiFields.add("emailTutorLaboral");
    openapiFields.add("telefonoTutorLaboral");
    openapiFields.add("activo");
    openapiFields.add("alumnos");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Empresa
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Empresa.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Empresa is not found in the empty JSON string", Empresa.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Empresa.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Empresa` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("nombreEmpresa") != null && !jsonObj.get("nombreEmpresa").isJsonNull()) && !jsonObj.get("nombreEmpresa").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nombreEmpresa` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nombreEmpresa").toString()));
      }
      if ((jsonObj.get("tutorLaboral") != null && !jsonObj.get("tutorLaboral").isJsonNull()) && !jsonObj.get("tutorLaboral").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tutorLaboral` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tutorLaboral").toString()));
      }
      if ((jsonObj.get("emailTutorLaboral") != null && !jsonObj.get("emailTutorLaboral").isJsonNull()) && !jsonObj.get("emailTutorLaboral").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `emailTutorLaboral` to be a primitive type in the JSON string but got `%s`", jsonObj.get("emailTutorLaboral").toString()));
      }
      if ((jsonObj.get("telefonoTutorLaboral") != null && !jsonObj.get("telefonoTutorLaboral").isJsonNull()) && !jsonObj.get("telefonoTutorLaboral").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `telefonoTutorLaboral` to be a primitive type in the JSON string but got `%s`", jsonObj.get("telefonoTutorLaboral").toString()));
      }
      if (jsonObj.get("alumnos") != null && !jsonObj.get("alumnos").isJsonNull()) {
        JsonArray jsonArrayalumnos = jsonObj.getAsJsonArray("alumnos");
        if (jsonArrayalumnos != null) {
          // ensure the json data is an array
          if (!jsonObj.get("alumnos").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `alumnos` to be an array in the JSON string but got `%s`", jsonObj.get("alumnos").toString()));
          }

          // validate the optional field `alumnos` (array)
          for (int i = 0; i < jsonArrayalumnos.size(); i++) {
            Alumno.validateJsonElement(jsonArrayalumnos.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Empresa.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Empresa' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Empresa> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Empresa.class));

       return (TypeAdapter<T>) new TypeAdapter<Empresa>() {
           @Override
           public void write(JsonWriter out, Empresa value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Empresa read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Empresa given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Empresa
   * @throws IOException if the JSON string is invalid with respect to Empresa
   */
  public static Empresa fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Empresa.class);
  }

  /**
   * Convert an instance of Empresa to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

