/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Alumno;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Usuario
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-18T17:33:28.589002300+01:00[Europe/Madrid]", comments = "Generator version: 7.11.0")
public class Usuario {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Long id;

  public static final String SERIALIZED_NAME_NOMBRE_USUARIO = "nombreUsuario";
  @SerializedName(SERIALIZED_NAME_NOMBRE_USUARIO)
  @javax.annotation.Nullable
  private String nombreUsuario;

  public static final String SERIALIZED_NAME_CONTRASENA = "contrasena";
  @SerializedName(SERIALIZED_NAME_CONTRASENA)
  @javax.annotation.Nullable
  private String contrasena;

  public static final String SERIALIZED_NAME_PERFIL = "perfil";
  @SerializedName(SERIALIZED_NAME_PERFIL)
  @javax.annotation.Nullable
  private String perfil;

  public static final String SERIALIZED_NAME_USUARIO_ASOCIADO = "usuarioAsociado";
  @SerializedName(SERIALIZED_NAME_USUARIO_ASOCIADO)
  @javax.annotation.Nullable
  private Alumno usuarioAsociado;

  public static final String SERIALIZED_NAME_ACTIVO = "activo";
  @SerializedName(SERIALIZED_NAME_ACTIVO)
  @javax.annotation.Nullable
  private Boolean activo;

  public Usuario() {
  }

  public Usuario id(@javax.annotation.Nullable Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Long getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }


  public Usuario nombreUsuario(@javax.annotation.Nullable String nombreUsuario) {
    this.nombreUsuario = nombreUsuario;
    return this;
  }

  /**
   * Get nombreUsuario
   * @return nombreUsuario
   */
  @javax.annotation.Nullable
  public String getNombreUsuario() {
    return nombreUsuario;
  }

  public void setNombreUsuario(@javax.annotation.Nullable String nombreUsuario) {
    this.nombreUsuario = nombreUsuario;
  }


  public Usuario contrasena(@javax.annotation.Nullable String contrasena) {
    this.contrasena = contrasena;
    return this;
  }

  /**
   * Get contrasena
   * @return contrasena
   */
  @javax.annotation.Nullable
  public String getContrasena() {
    return contrasena;
  }

  public void setContrasena(@javax.annotation.Nullable String contrasena) {
    this.contrasena = contrasena;
  }


  public Usuario perfil(@javax.annotation.Nullable String perfil) {
    this.perfil = perfil;
    return this;
  }

  /**
   * Get perfil
   * @return perfil
   */
  @javax.annotation.Nullable
  public String getPerfil() {
    return perfil;
  }

  public void setPerfil(@javax.annotation.Nullable String perfil) {
    this.perfil = perfil;
  }


  public Usuario usuarioAsociado(@javax.annotation.Nullable Alumno usuarioAsociado) {
    this.usuarioAsociado = usuarioAsociado;
    return this;
  }

  /**
   * Get usuarioAsociado
   * @return usuarioAsociado
   */
  @javax.annotation.Nullable
  public Alumno getUsuarioAsociado() {
    return usuarioAsociado;
  }

  public void setUsuarioAsociado(@javax.annotation.Nullable Alumno usuarioAsociado) {
    this.usuarioAsociado = usuarioAsociado;
  }


  public Usuario activo(@javax.annotation.Nullable Boolean activo) {
    this.activo = activo;
    return this;
  }

  /**
   * Get activo
   * @return activo
   */
  @javax.annotation.Nullable
  public Boolean getActivo() {
    return activo;
  }

  public void setActivo(@javax.annotation.Nullable Boolean activo) {
    this.activo = activo;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Usuario usuario = (Usuario) o;
    return Objects.equals(this.id, usuario.id) &&
        Objects.equals(this.nombreUsuario, usuario.nombreUsuario) &&
        Objects.equals(this.contrasena, usuario.contrasena) &&
        Objects.equals(this.perfil, usuario.perfil) &&
        Objects.equals(this.usuarioAsociado, usuario.usuarioAsociado) &&
        Objects.equals(this.activo, usuario.activo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nombreUsuario, contrasena, perfil, usuarioAsociado, activo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Usuario {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nombreUsuario: ").append(toIndentedString(nombreUsuario)).append("\n");
    sb.append("    contrasena: ").append(toIndentedString(contrasena)).append("\n");
    sb.append("    perfil: ").append(toIndentedString(perfil)).append("\n");
    sb.append("    usuarioAsociado: ").append(toIndentedString(usuarioAsociado)).append("\n");
    sb.append("    activo: ").append(toIndentedString(activo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("nombreUsuario");
    openapiFields.add("contrasena");
    openapiFields.add("perfil");
    openapiFields.add("usuarioAsociado");
    openapiFields.add("activo");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Usuario
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Usuario.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Usuario is not found in the empty JSON string", Usuario.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Usuario.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Usuario` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("nombreUsuario") != null && !jsonObj.get("nombreUsuario").isJsonNull()) && !jsonObj.get("nombreUsuario").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nombreUsuario` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nombreUsuario").toString()));
      }
      if ((jsonObj.get("contrasena") != null && !jsonObj.get("contrasena").isJsonNull()) && !jsonObj.get("contrasena").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `contrasena` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contrasena").toString()));
      }
      if ((jsonObj.get("perfil") != null && !jsonObj.get("perfil").isJsonNull()) && !jsonObj.get("perfil").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `perfil` to be a primitive type in the JSON string but got `%s`", jsonObj.get("perfil").toString()));
      }
      // validate the optional field `usuarioAsociado`
      if (jsonObj.get("usuarioAsociado") != null && !jsonObj.get("usuarioAsociado").isJsonNull()) {
        Alumno.validateJsonElement(jsonObj.get("usuarioAsociado"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Usuario.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Usuario' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Usuario> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Usuario.class));

       return (TypeAdapter<T>) new TypeAdapter<Usuario>() {
           @Override
           public void write(JsonWriter out, Usuario value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Usuario read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Usuario given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Usuario
   * @throws IOException if the JSON string is invalid with respect to Usuario
   */
  public static Usuario fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Usuario.class);
  }

  /**
   * Convert an instance of Usuario to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

