/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Empresa;
import org.openapitools.client.model.RegistroPractica;
import org.openapitools.client.model.Tutor;
import org.openapitools.client.model.Usuario;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Alumno
 */
public class AlumnoTest {
    private final Alumno model = new Alumno();

    /**
     * Model tests for Alumno
     */
    @Test
    public void testAlumno() {
        // TODO: test Alumno
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'nombreCompleto'
     */
    @Test
    public void nombreCompletoTest() {
        // TODO: test nombreCompleto
    }

    /**
     * Test the property 'activo'
     */
    @Test
    public void activoTest() {
        // TODO: test activo
    }

    /**
     * Test the property 'ciclo'
     */
    @Test
    public void cicloTest() {
        // TODO: test ciclo
    }

    /**
     * Test the property 'evaluacion'
     */
    @Test
    public void evaluacionTest() {
        // TODO: test evaluacion
    }

    /**
     * Test the property 'anioCurso'
     */
    @Test
    public void anioCursoTest() {
        // TODO: test anioCurso
    }

    /**
     * Test the property 'tutorDocente'
     */
    @Test
    public void tutorDocenteTest() {
        // TODO: test tutorDocente
    }

    /**
     * Test the property 'empresa'
     */
    @Test
    public void empresaTest() {
        // TODO: test empresa
    }

    /**
     * Test the property 'usuario'
     */
    @Test
    public void usuarioTest() {
        // TODO: test usuario
    }

    /**
     * Test the property 'registrosPractica'
     */
    @Test
    public void registrosPracticaTest() {
        // TODO: test registrosPractica
    }

}
