/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Alumno;
import org.openapitools.client.model.Fecha;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RegistroPractica
 */
public class RegistroPracticaTest {
    private final RegistroPractica model = new RegistroPractica();

    /**
     * Model tests for RegistroPractica
     */
    @Test
    public void testRegistroPractica() {
        // TODO: test RegistroPractica
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'alumno'
     */
    @Test
    public void alumnoTest() {
        // TODO: test alumno
    }

    /**
     * Test the property 'fecha'
     */
    @Test
    public void fechaTest() {
        // TODO: test fecha
    }

    /**
     * Test the property 'horas'
     */
    @Test
    public void horasTest() {
        // TODO: test horas
    }

    /**
     * Test the property 'descripcion'
     */
    @Test
    public void descripcionTest() {
        // TODO: test descripcion
    }

}
