/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Alumno;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Tutor
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-02T23:55:13.883603200+01:00[Europe/Madrid]", comments = "Generator version: 7.11.0")
public class Tutor {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Long id;

  public static final String SERIALIZED_NAME_NOMBRE_COMPLETO = "nombreCompleto";
  @SerializedName(SERIALIZED_NAME_NOMBRE_COMPLETO)
  @javax.annotation.Nullable
  private String nombreCompleto;

  public static final String SERIALIZED_NAME_ACTIVO = "activo";
  @SerializedName(SERIALIZED_NAME_ACTIVO)
  @javax.annotation.Nullable
  private Boolean activo;

  public static final String SERIALIZED_NAME_ALUMNOS = "alumnos";
  @SerializedName(SERIALIZED_NAME_ALUMNOS)
  @javax.annotation.Nullable
  private List<Alumno> alumnos = new ArrayList<>();

  public Tutor() {
  }

  public Tutor id(@javax.annotation.Nullable Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Long getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }


  public Tutor nombreCompleto(@javax.annotation.Nullable String nombreCompleto) {
    this.nombreCompleto = nombreCompleto;
    return this;
  }

  /**
   * Get nombreCompleto
   * @return nombreCompleto
   */
  @javax.annotation.Nullable
  public String getNombreCompleto() {
    return nombreCompleto;
  }

  public void setNombreCompleto(@javax.annotation.Nullable String nombreCompleto) {
    this.nombreCompleto = nombreCompleto;
  }


  public Tutor activo(@javax.annotation.Nullable Boolean activo) {
    this.activo = activo;
    return this;
  }

  /**
   * Get activo
   * @return activo
   */
  @javax.annotation.Nullable
  public Boolean getActivo() {
    return activo;
  }

  public void setActivo(@javax.annotation.Nullable Boolean activo) {
    this.activo = activo;
  }


  public Tutor alumnos(@javax.annotation.Nullable List<Alumno> alumnos) {
    this.alumnos = alumnos;
    return this;
  }

  public Tutor addAlumnosItem(Alumno alumnosItem) {
    if (this.alumnos == null) {
      this.alumnos = new ArrayList<>();
    }
    this.alumnos.add(alumnosItem);
    return this;
  }

  /**
   * Get alumnos
   * @return alumnos
   */
  @javax.annotation.Nullable
  public List<Alumno> getAlumnos() {
    return alumnos;
  }

  public void setAlumnos(@javax.annotation.Nullable List<Alumno> alumnos) {
    this.alumnos = alumnos;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tutor tutor = (Tutor) o;
    return Objects.equals(this.id, tutor.id) &&
        Objects.equals(this.nombreCompleto, tutor.nombreCompleto) &&
        Objects.equals(this.activo, tutor.activo) &&
        Objects.equals(this.alumnos, tutor.alumnos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nombreCompleto, activo, alumnos);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tutor {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nombreCompleto: ").append(toIndentedString(nombreCompleto)).append("\n");
    sb.append("    activo: ").append(toIndentedString(activo)).append("\n");
    sb.append("    alumnos: ").append(toIndentedString(alumnos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("nombreCompleto");
    openapiFields.add("activo");
    openapiFields.add("alumnos");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Tutor
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Tutor.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Tutor is not found in the empty JSON string", Tutor.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Tutor.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Tutor` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("nombreCompleto") != null && !jsonObj.get("nombreCompleto").isJsonNull()) && !jsonObj.get("nombreCompleto").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nombreCompleto` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nombreCompleto").toString()));
      }
      if (jsonObj.get("alumnos") != null && !jsonObj.get("alumnos").isJsonNull()) {
        JsonArray jsonArrayalumnos = jsonObj.getAsJsonArray("alumnos");
        if (jsonArrayalumnos != null) {
          // ensure the json data is an array
          if (!jsonObj.get("alumnos").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `alumnos` to be an array in the JSON string but got `%s`", jsonObj.get("alumnos").toString()));
          }

          // validate the optional field `alumnos` (array)
          for (int i = 0; i < jsonArrayalumnos.size(); i++) {
            Alumno.validateJsonElement(jsonArrayalumnos.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Tutor.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Tutor' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Tutor> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Tutor.class));

       return (TypeAdapter<T>) new TypeAdapter<Tutor>() {
           @Override
           public void write(JsonWriter out, Tutor value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Tutor read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Tutor given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Tutor
   * @throws IOException if the JSON string is invalid with respect to Tutor
   */
  public static Tutor fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Tutor.class);
  }

  /**
   * Convert an instance of Tutor to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

